language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
      - pandoc
      - jackd2
install:
  - pip install -U pip
  - pip install -U setuptools wheel
  - pip install -U pytest pytest-cov pytest-xdist coveralls
  - pip install -U -r requirements.txt
  - python setup.py build_ext --force --inplace --define CYTHON_TRACE_NOGIL
script:
  - py.test -n=auto --cov-config .coveragerc --cov=pyltc
after_success:
  - coverage combine
  - coveralls
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  on:
    python: "3.5"
    tags: true
  user: nocarryr
  password:
    secure: C6UEEhM/LqhGhEN/p33j2aLDeQlcQvXiEMWH+nnz5RQOEBiFT9vskWiZmOpLq63vWQQAknjloo9WQ4e1pvVTvkzlWyKZ+Anipu8aC/tSAyKQ3snPtAgjH8SVBBZMlU4ks9GQo0+uBuD77Ux9Gkp3+uEjkAVb1FrUGkhdTGmZoz96nvWpnnS+YeqxlNx6N2lFuFetsW9kbTP6WSDOph2AasFW1X91Lm5TSxeNpy2tpz+eLFgkbBrw5u0790OIVnxWy7L5DgsejKfhAZgyPRCHcbKwygo8KvssrmsSVLT62yQlqehRmN2ui1bH0YPqib4Saz78saFcslLLnjjf9Pk5sXcFtn61y2B1l+gT9bQZCoDVLiP8ru335CmoJqvbzJooF/7EbzCaC2m9vr0LbKXsqcgc0+j3fYTx8IZoYK1KplPFD4nhMXNnWBHfvxsiww4sqQu7DvGFFydlMgNpZcrbCk/hBzVYeZPKsGNUVkvpPAhjtJ4ULJiFmcKBbJ4CzUEYuOw3HAI+FGpJMvvU/l7Rg9Xv/TbTdjHPX+DWkF9jdXMClTMu0Iki6Xi4Ap2KoOsOzMmP69AhzCTzSrW9ANjb/YboFAdJZVDW9VMHYp0CGIavdKhWf8kGDOcZy6kf6CMR7HKJmn4PMvwRSaRaKoSkBzxJqELg7d+evHVM8WgB8S0=
